### PR TITLE
Fix path backslashes in catkin_package.cmake

### PR DESCRIPTION
**Pull request by ojura**
I occasionally get an error in `list_append_unique.cmake` which originates here due to backslashes being interpreted as escape chars. Not sure what's the best place to fix it, this is a band-aid.

### CODE REVIEW

**Comment by seanyen-msft** [comment]
Can you elaborate more how do you reproduce the problem? Maybe some reproducing steps?

**Comment by ojura** [comment]
I’ll try to, but the confusing part is that it was happening sporadically.

**Comment by ojura** [comment]
Another issue I think may be related is that it seems that CWD is important when doing `call C:\opt\ros\melodic\x64\setup.bat`. It fails from the root of C:, for example: 

    C:/opt/python27amd64/python.exe: can't open file '_parent_package_path.py': [Errno 2] No such file or directory
    Could Not Find c:\_parent_package_path.py

Anyway, what I experienced is that I would call `catkin_make_isolated` from C:\catkin_ws (with the package sources being in catkin_ws\src - no `catkin_init_workspace` is necessary, fyi :-)). catkin would build cartographer successfully, but when it would move on to build cartographer_ros_msgs (or cartographer_ros, I forgot), it would error out at line 10 in `list_append_unique.cmake` due to the argument containing single backslashes being interpreted as escapes. The call site of `list_append_unique` was where I added the string replace in this PR.

Then, when I would clear out build, devel and install (_isolated) and try again, it succeeds. Beats me. All I know is that it looks like there are certain scenarios where `workspace` in this loop can end up containing backslashes.

**Comment by ojura** [comment]
```
<== Finished processing package [1 of 4]: 'cartographer'

==> Processing catkin package: 'cartographer_ros_msgs'
==> Building with env: 'C:\catkin_ws\install_isolated\env.bat'
build.ninja exists, skipping explicit cmake invocation...
==> ninja build.ninja in 'C:\catkin_ws\build_isolated\cartographer_ros_msgs'
[0/1] Re-running CMake...
-- Using CATKIN_DEVEL_PREFIX: C:/catkin_ws/devel_isolated/cartographer_ros_msgs
-- Using CMAKE_PREFIX_PATH: C:/catkin_ws/install_isolated;C:\catkin_ws\install_isolated;C:/opt/ros/melodic/x64;C:/opt/rosdeps/x64
-- This workspace overlays: C:/catkin_ws/install_isolated;C:\catkin_ws\install_isolated;C:/opt/ros/melodic/x64
-- Using PYTHON_EXECUTABLE: C:/opt/python27amd64/python.exe
-- Using default Python package layout
-- Using empy: C:/opt/python27amd64/lib/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: C:/catkin_ws/build_isolated/cartographer_ros_msgs/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: C:/opt/python27amd64/Scripts/nosetests-2.7.exe
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- cartographer_ros_msgs: 15 messages, 6 services
status!!!!!!!!!!!!!!!! C:/catkin_ws/install_isolated
status!!!!!!!!!!!!!!!! C:\catkin_ws\install_isolated
CMake Error at C:/opt/ros/melodic/x64/share/catkin/cmake/list_append_unique.cmake:10 (foreach):
  Syntax error in cmake code at

    C:/opt/ros/melodic/x64/share/catkin/cmake/list_append_unique.cmake:10

  when parsing string

    C:\catkin_ws\install_isolated/lib

  Invalid escape sequence \c
Call Stack (most recent call first):
  C:/opt/ros/melodic/x64/share/catkin/cmake/catkin_package.cmake:249 (list_append_unique)
  C:/opt/ros/melodic/x64/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:62 (catkin_package)
```

**Comment by seanyen-msft** [comment]
Looks like the CATKIN_WORKSPACES is based on CMAKE_PREFIX_PATH, and I noticed in the full log which contains CMAKE path and Windows native path usage mixed. It would be interesting to see why it ends up this case there. Under C:\catkin_ws\install_isolated, can you see any Windows native path not being processed correctly in _setup_util.py?

This was fixed in another commit: https://github.com/ms-iot/catkin/commit/91a4718c6c2c9dc1886a07a97ac8470c8bb39533 but there might be some cases not considered & tested (or checking if your local _setup_util.py looks the same as this one...)

**Comment by ojura** [comment]
@seanyen-msft the problem is libcartographer. It's a plain CMake package which is built first. The install space does not contain _setup_util.py after just libcartographer (a plain CMake package) is installed.  Here's how setup.bat looks:

```
@echo off
REM generated from catkin.builder module
REM Prepend to the environment
set CMAKE_PREFIX_PATH=C:\catkin_ws\install_isolated;%CMAKE_PREFIX_PATH%
set LD_LIBRARY_PATH=C:\catkin_ws\install_isolated\lib;%LD_LIBRARY_PATH%
set PATH=C:\catkin_ws\install_isolated\bin;%PATH%
set PKG_CONFIG_PATH=C:\catkin_ws\install_isolated\lib\pkgconfig;%PKG_CONFIG_PATH%
set PYTHONPATH=C:\catkin_ws\install_isolated\lib\site-packages;%PYTHONPATH%
```

**Comment by ojura** [comment]
@seanyen-msft I updated the PR (haven't yet tried it out - this is more like a suggestion; maybe there are other paths which should also get the same treatment).

**Comment by seanyen-msft** [comment]
@ojura Thanks for pointing out the root cause! I made some adjustments to normalize the CMAKE_PREFIX_PATH on a upper stream call path and will merge it today.

**Pull request merged**
